### ISSUE TITLE
Here is the Yaml

### ISSUE THREAD

**Issue by Shebatrice** [Shebatrice/shebalatrice#1]
Here is the Yaml

```yaml
# Synthwave '84
accent:
    left: "#f92aad"
    right: "#848bbd"
background:
  top: "#241b2f"
  bottom: "#191621"
details: darker
foreground: "#f1f1f1"
terminal_colors:
  normal:
    black: "#382C4D"
    blue: "#34d3fb"
    cyan: "#36f9f6"
    green: "#72f1b8"
    magenta: "#f92aad"
    red: "#fe4450"
    white: "#f2ebe0"
    yellow: "#fede5d"
  bright:
    black: "#7b6a98"
    blue: "#aaeeff"
    cyan: "#9efffd"
    green: "#c6ffe5"
    magenta: "#ffa8df"
    red: "#ff7d86"
    white: "#f1f1f1"
    yellow: "#fff0b4"
```

__Originally posted by @spencerthayer in https://github.com/warpdotdev/themes/issues/53__
